services:
  - type: web
    name: exploding-kittens-api
    env: go
    rootDir: backend
    buildCommand: go build -o main .
    startCommand: ./main
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        sync: false
      - key: GIN_MODE
        value: release
      - key: JWT_SECRET
        generateValue: true
      - key: REDIS_URL
        value: redis://default:password@redis-12345.c1.us-east-1-1.ec2.cloud.redislabs.com:12345
      - key: ALLOWED_ORIGINS
        value: https://exploding-kittens.vercel.app